# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDigitsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(max_length=7)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('entityId', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewType', models.CharField(max_length=8)),
                ('entityId', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenterClass', models.CharField(default=b'', max_length=255, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('do_you_ever_buy_lottery_tickets', models.BooleanField()),
                ('why_or_why_not_audio', models.FileField(upload_to=b'audio/%Y_%m_%d_%h_%M_%s')),
                ('have_you_ever_won_the_lottery', models.BooleanField()),
                ('most_won', models.CharField(max_length=255)),
                ('money_spent_on_lottery_in_average_week', models.CharField(max_length=255)),
                ('jackpot_audio', models.FileField(blank=True, upload_to=b'audio/%Y_%m_%d_%h_%M_%s')),
                ('photo', models.FileField(upload_to=b'photo/%Y_%m_%d_%h_%M_%s')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=255)),
                ('do_you_sell_lottery_tickets', models.BooleanField()),
                ('why_or_why_not_audio', models.FileField(upload_to=b'audio/%Y_%m_%d_%h_%M_%s')),
                ('customers_in_a_day', models.CharField(blank=True, max_length=255)),
                ('percentage_buy_lottery_tickets', models.IntegerField()),
                ('amount_tickets_bought_per_visit', models.CharField(blank=True, max_length=50)),
                ('why_or_why_not_lottery_neighborhood_audio', models.FileField(blank=True, upload_to=b'audio/%Y_%m_%d_%h_%M_%s')),
                ('photo', models.FileField(upload_to=b'photo/%Y_%m_%d_%h_%M_%s')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodStatistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('percent_income', models.CharField(max_length=255)),
                ('net_win', models.CharField(max_length=255)),
                ('daily_sale', models.CharField(max_length=255)),
                ('daily_win', models.CharField(max_length=255)),
                ('daily_income', models.CharField(max_length=255)),
                ('map_id', models.CharField(max_length=255)),
                ('total_households', models.CharField(max_length=255)),
                ('total_18_and_up', models.CharField(max_length=255)),
                ('total_retailers', models.CharField(max_length=255)),
                ('adults_per_store', models.CharField(max_length=255)),
                ('net_loss_per_store', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('className', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.School')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teamPhoto', models.FileField(upload_to=b'photo/%Y_%m_%d_%h_%M_%s_team_photo')),
                ('coverPhoto', models.FileField(upload_to=b'photo/%Y_%m_%d_%h_%M_%s_cover_photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TourAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Student')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=b'photo/%Y_%m_%d_%h_%M_%s_slide_photo')),
                ('text', models.TextField()),
                ('link', models.TextField()),
                ('audio', models.FileField(upload_to=b'audio/%Y_%m_%d_%h_%M_%s_slide_audio')),
                ('sequence', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Tour')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Team'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Location'),
        ),
        migrations.AddField(
            model_name='interview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citi_digits.Student'),
        ),
    ]
